import type { ScreenerConfig } from "../screenerTypes";

export const castConfig: ScreenerConfig = {
  id: "cast",
  title: "CAST — Screening de Autismo",
  description: "Cuestionario de 39 preguntas sobre cómo se relaciona, comunica y se comporta tu hijo en su día a día.",
  durationEstimate: "~10 minutos",
  ageRangeMonths: { min: 48, max: 132 },
  redirects: {
    tooYoung: {
      message:
        "Este cuestionario aplica para niños de 4 a 11 años. Si tu hijo es menor de 4 años, visita nuestro screener M-CHAT-R.",
      ctaLabel: "Ir al M-CHAT-R",
      ctaUrl: "/screening-mchat",
    },
    tooOld: {
      message: "Este cuestionario no aplica para la edad de tu hijo/a. Te invitamos a contactar directamente a Brilus.",
      ctaLabel: "Contactar a Brilus",
      ctaUrl: "/contacto",
    },
  },
  privacyNoticeText:
    "Acepto el Aviso de Privacidad. Consiento que mis datos sean tratados de forma confidencial por Brilus y la Unidad de Neurodesarrollo del Hospital Español.",
  questions: [
    { id: 1, section: "main", type: "yesno", text: "¿Disfruta fácilmente al jugar con otros niños?" },
    { id: 2, section: "main", type: "yesno", text: "¿Se acerca espontáneamente a usted para conversar?" },
    { id: 3, section: "main", type: "yesno", text: "¿Hablaba a los 2 años de edad?" },
    { id: 4, section: "main", type: "yesno", text: "¿Disfruta al realizar deportes?" },
    { id: 5, section: "main", type: "yesno", text: "¿Es importante para él/ella encajar con sus compañeros?" },
    { id: 6, section: "main", type: "yesno", text: "¿Parece advertir detalles inusuales que el resto no percibe?" },
    { id: 7, section: "main", type: "yesno", text: "¿Suele tomar las cosas que le dicen de forma literal?" },
    {
      id: 8,
      section: "main",
      type: "yesno",
      text: "¿A los 3 años de edad pasaba gran cantidad de tiempo jugando a ser súper héroe o jugando a tomar el té con muñecos (juego de roles)?",
    },
    {
      id: 9,
      section: "main",
      type: "yesno",
      text: "¿Le gusta realizar las cosas una y otra vez, y de la misma forma todas las veces?",
    },
    { id: 10, section: "main", type: "yesno", text: "¿Interactúa fácilmente con otros niños?" },
    { id: 11, section: "main", type: "yesno", text: "¿Puede mantener una conversación de ida y vuelta?" },
    { id: 12, section: "main", type: "yesno", text: "¿Lee apropiadamente para su edad?" },
    { id: 13, section: "main", type: "yesno", text: "¿Presenta generalmente los mismos intereses que sus compañeros?" },
    {
      id: 14,
      section: "main",
      type: "yesno",
      text: "¿Presenta algún interés en particular que le deja poco tiempo para realizar el resto de sus cosas?",
    },
    { id: 15, section: "main", type: "yesno", text: "¿Tiene amigos(as), más que sólo conocidos?" },
    {
      id: 16,
      section: "main",
      type: "yesno",
      text: "¿Trae a menudo cosas que le interesan para mostrárselas a usted?",
    },
    { id: 17, section: "main", type: "yesno", text: "¿Disfruta él/ella bromeando?" },
    { id: 18, section: "main", type: "yesno", text: "¿Tiene dificultad para entender las reglas de cortesía?" },
    { id: 19, section: "main", type: "yesno", text: "¿Pareciera tener una memoria excepcional para los detalles?" },
    {
      id: 20,
      section: "main",
      type: "yesno",
      text: "¿Su voz es inusual (ej. excesivamente adulta, plana, o muy monótona)?",
    },
    { id: 21, section: "main", type: "yesno", text: "¿El resto de las personas son importantes para él/ella?" },
    { id: 22, section: "main", type: "yesno", text: "¿Se puede vestir solo(a)?" },
    { id: 23, section: "main", type: "yesno", text: "¿Se adecúa a los turnos en una conversación?" },
    {
      id: 24,
      section: "main",
      type: "yesno",
      text: "¿Puede jugar imaginativamente con otros niños y participar de juegos de roles (jugar a ser mesero, bombero, etc.)?",
    },
    {
      id: 25,
      section: "main",
      type: "yesno",
      text: "¿Hace o dice a menudo cosas que son falta de tacto o socialmente inapropiadas?",
    },
    { id: 26, section: "main", type: "yesno", text: "¿Puede contar hasta 50 sin omitir números?" },
    {
      id: 27,
      section: "main",
      type: "yesno",
      text: "¿Presenta contacto ocular normal al conversar (mirar a los ojos)?",
    },
    { id: 28, section: "main", type: "yesno", text: "¿Presenta algún movimiento inusual y repetitivo?" },
    {
      id: 29,
      section: "main",
      type: "yesno",
      text: "¿Su comportamiento social es muy unilateral y siempre en sus propios términos?",
    },
    { id: 30, section: "main", type: "yesno", text: '¿A veces dice "tú" o "él/ella" cuando quiere decir "yo"?' },
    {
      id: 31,
      section: "main",
      type: "yesno",
      text: "¿Prefiere las actividades imaginativas tales como actuar o contar cuentos más que los números o memorizar datos?",
    },
    { id: 32, section: "main", type: "yesno", text: "¿A veces quien lo/la escucha no comprende sobre lo que habla?" },
    { id: 33, section: "main", type: "yesno", text: "¿Puede andar en bicicleta (aunque sea con rueditas laterales)?" },
    {
      id: 34,
      section: "main",
      type: "yesno",
      text: "¿Trata de imponer rutinas o imponérselas a otros, llegando incluso al punto de causar problemas?",
    },
    { id: 35, section: "main", type: "yesno", text: "¿Le importa cómo es percibido por el resto?" },
    {
      id: 36,
      section: "main",
      type: "yesno",
      text: "¿Vuelca a menudo las conversaciones hacia sus temas favoritos antes de continuar con el tema que la otra persona expone?",
    },
    { id: 37, section: "main", type: "yesno", text: "¿Dice frases inusuales o extrañas?" },
    {
      id: 38,
      section: "info",
      type: "yesno_with_text",
      text: "¿Algún profesor o profesional de la salud ha expresado alguna vez algo concerniente a su desarrollo?",
      conditionalTextLabel: "Si es sí, especifique",
    },
    {
      id: 39,
      section: "info",
      type: "yesno_subitems",
      text: "¿En algún momento se le ha diagnosticado alguno de los siguientes?",
      subitems: [
        { id: "lenguaje", label: "Retraso del Lenguaje" },
        { id: "tdah", label: "TDAH" },
        { id: "visual_auditivo", label: "Alteraciones visuales o auditivas" },
        { id: "tea", label: "Condición del espectro autista" },
        { id: "fisica", label: "Incapacidad física" },
        { id: "otro", label: "Otro (especificar)", hasConditionalText: true },
      ],
    },
  ],
  scoringRules: {
    yesRiskIds: [6, 7, 9, 14, 18, 19, 20, 25, 28, 29, 30, 32, 34, 36, 37],
    noRiskIds: [1, 2, 5, 8, 10, 11, 13, 15, 16, 17, 21, 23, 24, 27, 31, 35],
    nonScoredIds: [3, 4, 12, 22, 26, 33, 38, 39],
    maxScore: 31,
    riskLevels: [
      { label: "Bajo Riesgo", min: 0, max: 14 },
      { label: "Riesgo Medio", min: 15, max: 22 },
      { label: "Alto Riesgo", min: 23, max: 31 },
    ],
  },
  closingPage: {
    title: "¡Gracias por completar el cuestionario!",
    thankYouMessage: "Hemos recibido tus respuestas correctamente.",
    nextStepsMessage: "Nuestro equipo te contactará para orientarte sobre los próximos pasos.",
    resourceLinks: [{ label: "Guías para familias", url: "/nuestros-blogs" }],
  },
};
