// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dozlintkzvgtfjlflkyp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvemxpbnRrenZndGZqbGZsa3lwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk5MDEwNzcsImV4cCI6MjA3NTQ3NzA3N30.BgI5poUTuFJ7OfyfQYmKnyW9lnyRqkL_YKV0zXG7uD4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});