import type { ServiceLinkCard } from "@/types/service-page";

export const SERVICE_CARDS: Record<"casa" | "centro" | "escuela" | "padres" | "sombra" | "diagnostico", ServiceLinkCard> = {
  casa: {
    variant: "casa",
    badge: "En casa",
    title: "Terapia en casa",
    subtitle: "En su entorno, con su familia",
    ctaLabel: "Agendar cita",
    href: "/in-home",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/in-home/Hero%20inhome.webp",
  },
  centro: {
    variant: "centro",
    badge: "En el centro",
    title: "Terapia en el centro",
    subtitle: "Hospital Español",
    ctaLabel: "Conocé el centro",
    href: "/in-center",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/in-center/Hero%20incenter.webp",
  },
  escuela: {
    variant: "escuela",
    badge: "En la escuela",
    title: "Terapia en la escuela",
    subtitle: "Integración en el aula real",
    ctaLabel: "Ver sombra escolar",
    href: "/in-school",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/in-school/Hero%20inschool.webp",
  },
  padres: {
    variant: "padres" as never,
    badge: "Para padres",
    title: "Entrenamiento a padres",
    subtitle: "Herramientas para el día a día",
    ctaLabel: "Inscribirse",
    href: "/servicios/entrenamiento-padres",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/Home/entrenamiento-padres.webp",
  },
  sombra: {
    variant: "sombra" as never,
    badge: "Sombra escolar",
    title: "Sombra Escolar Terapéutica",
    subtitle: "Inclusión real en el aula",
    ctaLabel: "Saber más",
    href: "/servicios/sombra-escolar",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/in-school/Hero%20inschool.webp",
  },
  diagnostico: {
    variant: "diagnostico" as never,
    badge: "Diagnóstico",
    title: "Evaluación Diagnóstica",
    subtitle: "Evaluamos y orientamos los próximos pasos",
    ctaLabel: "Hacer screening",
    href: "/diagnostico",
    image: "https://dozlintkzvgtfjlflkyp.supabase.co/storage/v1/object/public/Photos/Home/entrenamiento-padres.webp",
  },
};
